### ISSUE TITLE
rare bug in Abelian array reshape args calculation

### ISSUE THREAD

**Issue by sjdu10** [jcmgray/symmray#3]
Two-line code reproduction of the error:
`from symmray.abelian_core import  calc_reshape_args`
`calc_reshape_arges(shape=(4,4,4), newshape=(16,4), subsizes=(None,None,(4,4))`

In the function `calc_reshape_arge`, when it is trying to detect unfusing, it uses a condition `if subsizes[i] is not None and subsizes[i][0] == dj:` in line 334 of `symmray.abeleian_core`, however the `subsizes[i][0] == dj` seems to only be a necessary condition. It is possible that the first dim of the subsizes coincide with a dim in the newshape, but actually no unfusing is happening (like in the example here the first 4 in the (4,4) of the subsizes coincides with the 4 in the newshape, so the code determines that an unfusing is happening, but this is not true).

My personal workaround is to enhance the condition to `if subsizes[i] is not None and subsizes[i][0] == dj and j != ndim_new - 1 and subsizes[i][1] == newshape[j + 1]:`, where I compare at least two dimensions of the subsizes and newshape, which is probably more 'necessary' for unfusing.

It may be good if there's a sufficient and necessary condition to detect unfusing.

**Comment by jcmgray** [comment]
Thanks, have hopefully fixed and added test for in https://github.com/jcmgray/symmray/commit/32f150d769bb7ad60d92ae205cee7d76a321eb02.
