### ISSUE TITLE
Error when handling oddpos with empty FermionicArray

### ISSUE THREAD

**Issue by sjdu10** [jcmgray/symmray#5]
Error reproduction:
```
from symmray.abelian_core import _tensordot_via_fused, drop_misaligned_sectors
import symmray as sr

a = sr.FermionicArray.from_blocks(blocks={(0,):1}, charge=0, symmetry='Z2', duals=(True,))
b = sr.FermionicArray.from_blocks(blocks={(1,):1}, charge=1, symmetry='Z2', duals=(False,), oddpos=1)
_tensordot_via_fused(a, b, axes_a=(0,), axes_b=(0,), left_axes=(),right_axes=())
```

..would give AssertionError, as in `_tensordot_via_fused` the way it deals with empty array (no matching blocks) is to call copy_with on array `a` with combined charge `a.symmetry.combine(a.charge, b.charge)`. But for FermionicArray when odd charge is presented I guess it requires an oddpos to initialize the array, which cause the error.

My workaround is to modify the logic of returning empty array in `_tensordot_via_fused` from:
```
    if not a.blocks or not b.blocks:
        # no aligned sectors, return empty array
        return a.copy_with(
            indices=without(a.indices, axes_a) + without(b.indices, axes_b),
            charge=a.symmetry.combine(a.charge, b.charge),
            blocks={},
        )
```

to:

```
    if not a.blocks or not b.blocks:
        # no aligned sectors, return empty array
        ts = a if a.charge != 0 else b
        return ts.copy_with(
            indices=without(a.indices, axes_a) + without(b.indices, axes_b),
            charge=a.symmetry.combine(a.charge, b.charge),
            blocks={},
        )
```
which seems to work fine for me.

**Comment by jcmgray** [comment]
Yes I came across this, I think can be solved just by dropping the check in `FermionicArray.copy_with`, and relying on `tensordot_fermionic` to combine the oddpos charges correctly (though it is a zero tensor so shouldn't matter in some ways).
